### ISSUE TITLE
 Request for Comprehensive Documentation Section for Origin UI

### ISSUE THREAD

**Issue by AdityaSrivastava185** [origin-space/originui#97]
I would like to suggest adding a dedicated documentation section for the component library, aimed at helping users and beginners navigate and learn more easily. This section could provide detailed documentation for each component, including installation steps, usage examples, and copy-paste code snippets for quick integration into projects. This would greatly improve accessibility and enhance the learning experience for new users. Thank you!

**Comment by pasqualevitiello** [comment]
Hey @AdityaSrivastava185 thanks for your feedback! Right now I'm focusing on building out the core components first to make sure we have a solid foundation. Since the components are designed to be copy-paste with just dependency installation needed, I'm keeping things simple for now.

Once we have a more complete set of stable components, I'll definitely prioritize creating proper documentation with detailed guides and examples.
